// app/components/SearchCommand.tsx
"use client";

import Router from "next/router";
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import type { NavLink } from "./types";
import styles from "./SearchCommand.module.css";

interface SearchCommandProps {
  links: NavLink[];
  open: boolean;
  onClose: () => void;
}

type SearchItem = {
  label: string;
  href: string;
  desc?: string;
};

const FOCUSABLE_SELECTOR =
  'a[href], button:not([disabled]), textarea, input, select, [tabindex]:not([tabindex="-1"])';

function flattenLinks(links: NavLink[]): SearchItem[] {
  return links.flatMap((link) => {
    if (link.children && link.children.length > 0) {
      return [
        { label: link.label, href: link.href },
        ...link.children.map((child) => ({
          label: `${link.label} · ${child.label}`,
          href: child.href,
          desc: child.desc,
        })),
      ];
    }

    return [{ label: link.label, href: link.href }];
  });
}

export function SearchCommand({ links, open, onClose }: SearchCommandProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState("");

  const items = useMemo(() => flattenLinks(links), [links]);
  const results = useMemo(() => {
    const term = query.trim().toLowerCase();
    if (!term) {
      return items;
    }

    return items.filter((item) =>
      [item.label, item.desc, item.href]
        .filter(Boolean)
        .some((value) => value!.toLowerCase().includes(term))
    );
  }, [items, query]);

  useEffect(() => {
    if (!open) {
      setQuery("");
      return;
    }

    const node = containerRef.current;
    if (!node) {
      return;
    }

    const focusable = node.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
    const first = focusable[0] ?? null;
    const last = focusable[focusable.length - 1] ?? null;

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        onClose();
      }

      if (event.key === "Tab" && focusable.length > 0) {
        if (event.shiftKey && first && document.activeElement === first) {
          event.preventDefault();
          last?.focus();
        } else if (!event.shiftKey && last && document.activeElement === last) {
          event.preventDefault();
          first?.focus();
        }
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    window.requestAnimationFrame(() => {
      inputRef.current?.focus();
    });

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [open, onClose]);

  const handleNavigate = useCallback(
    (href: string) => {
      onClose();
      Router.push(href);
    },
    [onClose]
  );

  if (!open) {
    return null;
  }

  return (
    <div className={styles.overlay} role="presentation" onClick={onClose}>
      <div
        role="dialog"
        aria-modal="true"
        className={styles.dialog}
        ref={containerRef}
        onClick={(event) => event.stopPropagation()}
      >
        <header className={styles.header}>
          <div className={styles.badge} aria-hidden>
            Commande
          </div>
          <p className={styles.hint}>
            Tapez pour naviguer. Appuyez sur <kbd>Esc</kbd> pour fermer.
          </p>
        </header>
        <div className={styles.inputRow}>
          <svg aria-hidden="true" viewBox="0 0 24 24">
            <path
              d="M11 5a6 6 0 0 1 4.472 9.983l3.272 3.273a1 1 0 0 1-1.414 1.414l-3.273-3.272A6 6 0 1 1 11 5Zm0 2a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"
              fill="currentColor"
            />
          </svg>
          <input
            ref={inputRef}
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Rechercher une page..."
            className={styles.input}
            aria-label="Rechercher"
          />
          <kbd className={styles.shortcut}>⌘K</kbd>
        </div>
        <div className={styles.results}>
          {results.length === 0 ? (
            <p className={styles.empty}>Aucun résultat ne correspond à votre recherche.</p>
          ) : (
            <ul className={styles.list}>
              {results.map((item) => (
                <li key={item.href}>
                  <button
                    type="button"
                    className={styles.result}
                    onClick={() => handleNavigate(item.href)}
                  >
                    <span className={styles.resultLabel}>{item.label}</span>
                    <span className={styles.resultDesc}>{item.desc ?? item.href}</span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
}

// src/components/SearchCommand.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import type { NavLink } from "../types/navigation";
import styles from "./SearchCommand.module.css?module";

interface SearchCommandProps {
  links: NavLink[];
  open: boolean;
}

const props = defineProps<SearchCommandProps>();
const emit = defineEmits<{
  (event: "close"): void;
}>();

type SearchItem = {
  label: string;
  href: string;
  desc?: string;
};

const FOCUSABLE_SELECTOR =
  'a[href], button:not([disabled]), textarea, input, select, [tabindex]:not([tabindex="-1"])';

function flattenLinks(links: NavLink[]): SearchItem[] {
  return links.flatMap((link) => {
    if (link.children && link.children.length > 0) {
      return [
        { label: link.label, href: link.href },
        ...link.children.map((child) => ({
          label: `${link.label} · ${child.label}`,
          href: child.href,
          desc: child.desc,
        })),
      ];
    }
    return [{ label: link.label, href: link.href }];
  });
}

const containerRef = ref<HTMLDivElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
const query = ref("");
const router = useRouter();

const items = computed(() => flattenLinks(props.links ?? []));
const results = computed(() => {
  const term = query.value.trim().toLowerCase();
  if (!term) return items.value;
  return items.value.filter((item) =>
    [item.label, item.desc, item.href]
      .filter(Boolean)
      .some((value) => value!.toLowerCase().includes(term))
  );
});

function close() {
  emit("close");
}

async function handleNavigate(href: string) {
  await router.push(href);
  close();
}

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Escape") {
    event.preventDefault();
    close();
  }

  const node = containerRef.value;
  if (!node || event.key !== "Tab") return;
  const focusable = node.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
  if (focusable.length === 0) return;
  const first = focusable[0];
  const last = focusable[focusable.length - 1];
  if (event.shiftKey && document.activeElement === first) {
    event.preventDefault();
    last?.focus();
  } else if (!event.shiftKey && document.activeElement === last) {
    event.preventDefault();
    first?.focus();
  }
};

watch(
  () => props.open,
  (open) => {
    if (open) {
      query.value = "";
      document.addEventListener("keydown", handleKeyDown);
      nextTick(() => {
        window.requestAnimationFrame(() => inputRef.value?.focus());
      });
    } else {
      document.removeEventListener("keydown", handleKeyDown);
    }
  }
);

onMounted(() => {
  if (props.open) {
    document.addEventListener("keydown", handleKeyDown);
    nextTick(() => {
      window.requestAnimationFrame(() => inputRef.value?.focus());
    });
  }
});

onBeforeUnmount(() => {
  document.removeEventListener("keydown", handleKeyDown);
});
</script>

<template>
  <div v-if="open" :class="styles.overlay" role="presentation" @click="close">
    <div
      role="dialog"
      aria-modal="true"
      :class="styles.dialog"
      ref="containerRef"
      @click.stop
    >
      <header :class="styles.header">
        <div :class="styles.badge" aria-hidden="true">
          Commande
        </div>
        <p :class="styles.hint">
          Tapez pour naviguer. Appuyez sur <kbd>Esc</kbd> pour fermer.
        </p>
      </header>
      <div :class="styles.inputRow">
        <svg aria-hidden="true" viewBox="0 0 24 24">
          <path
            d="M11 5a6 6 0 0 1 4.472 9.983l3.272 3.273a1 1 0 0 1-1.414 1.414l-3.273-3.272A6 6 0 1 1 11 5Zm0 2a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"
            fill="currentColor"
          />
        </svg>
        <input
          ref="inputRef"
          v-model="query"
          placeholder="Rechercher une page..."
          :class="styles.input"
          aria-label="Rechercher"
        />
        <kbd :class="styles.shortcut">⌘K</kbd>
      </div>
      <div :class="styles.results">
        <p v-if="results.length === 0" :class="styles.empty">
          Aucun résultat ne correspond à votre recherche.
        </p>
        <ul v-else :class="styles.list">
          <li v-for="item in results" :key="item.href">
            <button type="button" :class="styles.result" @click="() => handleNavigate(item.href)">
              <span :class="styles.resultLabel">{{ item.label }}</span>
              <span :class="styles.resultDesc">{{ item.desc ?? item.href }}</span>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
